"""empty message

Revision ID: 397e87cecc98
Revises: 7843f93a953a
Create Date: 2021-10-13 18:29:37.768871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397e87cecc98'
down_revision = '7843f93a953a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=125), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'url', name='unique_fav_for_user')
    )
    op.add_column('user', sa.Column('user_name', sa.String(length=30), nullable=False))
    op.create_unique_constraint(None, 'user', ['user_name'])
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_name')
    op.drop_table('favorite')
    # ### end Alembic commands ###
